[options]
    # Colorsheme and colors
    colorscheme = "nord"
    colorscheme_bg = "dark" 
    enable_guicolors = true
   
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode_symbols = true
    
    buffer_index_type = 2
    windows_index_type = 1
    vimcompatible = false

[[layers]]
  name = "colorscheme"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 3

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lsp"
  filetypes = [
    "rust"
  ]
  [layers.override_cmd]
    rust = ["rls"]

