[options]
    # Color scheme and colors
    colorscheme = "nord"
    colorscheme_bg = "dark" 
    enable_guicolors = true
   
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    statusline_unicode_symbols = true
    
    buffer_index_type = 2
    windows_index_type = 1
    vimcompatible = false

    project_rooter_outermost = false

    relativenumber = false

    bootstrap_after = 'config#after'

# Enables color color scheme
[[layers]]
  name = "colorscheme"

# Enable auto complete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "cycle"

# Shell support
[[layers]]
name = 'shell'
default_position = 'top'
default_height = 3

# Git support
[[layers]]
    name = 'git'
[[layers]]
    name = 'VersionControl'

# Typescript language server
[[layers]]
  name = "lang#typescript"

# Rust language server
[[layers]]
  name = "lang#rust"

# JS language server
[[layers]]
  name = "lang#javascript"
  auto_fix = true
  format_on_save = true

# Tom layer
[[layers]]
  name = "lang#toml"

# Language protocol server
[[layers]]
  name = "lsp"
  filetypes = [
    "rust",
    "javascript"
  ]
  [layers.override_cmd]
    rust = ["rls"]

[[layers]]
  name = "format"

[[layers]]
  name = "checkers"

