#!/bin/sh

echo "Cheeking the last version of NVIM"
NVIM_LAST=$(curl --silent "https://api.github.com/repos/neovim/neovim/releases/latest" |
  grep '"tag_name":' |
  sed -E 's/.*"([^"]+)".*/\1/')
echo "The last version is: $NVIM_LAST"
NVIM_INSTALED=$(nvim --version | head -1 | sed -e "s|^[^0-9|v]*||" -e "s| .*||")
echo "The current installed version is: $NVIM_INSTALED"
if [ "$NVIM_LAST" != "$NVIM_INSTALED" ]; then
  echo "The NVIM version are different! Installing the last version..."
  curl -LO --silent https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
  chmod u+x nvim.appimage
  mv nvim.appimage ~/.local/bin/nvim
  echo "The new NVIM version ( $NVIM_LAST ) has been installed."
else
  echo "NVIM is in the last version ( $NVIM_INSTALED ), noting to do."
fi
