#!/bin/bash
set -e

echo "Install Gup"
go install github.com/nao1215/gup@latest
echo "Install Lazydocker"
go install github.com/jesseduffield/lazydocker@latest
echo "Install gopls"
go install golang.org/x/tools/gopls
echo "Install staticcheck"
go install honnef.co/go/tools/cmd/staticcheck
