#!/bin/sh

# Load nvm
NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

echo "Cheeking the last version of NVM"
NVM_LAST=$(curl --silent "https://api.github.com/repos/nvm-sh/nvm/releases/latest" |
  grep '"tag_name":' |
  sed -E 's/.*"([^"]+)".*/\1/')
echo "The last version is: $NVM_LAST"
NVM_INSTALED=$(nvm -v | sed -e "s/^/v/")
echo "The current installed version is: $NVM_INSTALED"
if [ "$NVM_LAST" != "$NVM_INSTALED" ]; then
  echo "The NVM version are different! Installing the last version..."
  curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/$NVM_LAST/install.sh" | bash
  echo "The new NVM version ( $NVM_LAST ) has been installed."
else
  echo "NVM is in the last version ( $NVM_INSTALED ), noting to do."
fi
