#!/bin/bash
set -e

echo 'Updating system 💻'
sudo apt update && sudo apt upgrade -y
echo 'Updating npm '
npm update -g
echo 'Updating snap 📸'
#sudo snap refresh
echo 'Updating flatpak'
flatpak update -y
echo 'Updating rust 🦀'
rustup update
echo 'Updating cargo 📦'
cargo install-update -a
