#!/bin/bash
set -e

echo "Updating system 💻"
brew upgrade
echo "update GO"
gup update
echo "Updating rust 🦀"
rustup update
echo "Updating cargo 📦"
cargo install-update -a
echo "Update Bun 🥟"
bun upgrade
