#!/bin/bash
set -e

echo "Updating system 💻"
sudo apt update && sudo apt upgrade -y
echo "Update NVM"
install-update-nvm
echo "update GO"
gup update
echo "Cleaning flatpak"
flatpak uninstall --unused -y
echo "Updating flatpak"
flatpak update -y
echo "Updating rust 🦀"
rustup update
echo "Updating cargo 📦"
cargo install-update -a
echo "Update Bun 🥟"
bun upgrade
