return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	event = { "BufReadPost", "BufNewFile" },
	cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
	opts = {
		ensure_installed = {
			"bash",
			"dockerfile",
			"html",
			"javascript",
			"json",
			"lua",
			"luadoc",
			"luap",
			"markdown",
			"markdown_inline",
			"query",
			"regex",
			"ron",
			"rust",
			"toml",
			"typescript",
			"vim",
			"vimdoc",
			"yaml",
			"gleam",
			"wgsl_bevy",
			-- Go
			"go",
			"gomod",
			"gowork",
			"gosum",
			-- Godot
			"gdscript",
			"gdshader",
			"godot_resource",
		},
		highlight = { enable = true },
		indent = { enable = true },
		auto_install = true,
	},
	config = function(_, opts)
		require("nvim-treesitter.configs").setup(opts)
	end,
}
